#!/usr/bin/env bash
set -euxo pipefail

npm install

npm run build

# https://github.com/slidevjs/slidev/issues/1872
if [ ! -f /usr/local/share/fonts/NotoColorEmoji.ttf ]; then
  curl -L --output NotoColorEmoji.ttf https://github.com/googlefonts/noto-emoji/raw/main/fonts/NotoColorEmoji.ttf
  sudo mv NotoColorEmoji.ttf /usr/local/share/fonts/
  fc-cache -fv
fi

npm run export-md-png
# https://github.com/slidevjs/slidev/issues/1874
mv slides-export.md dist/png.md
mv slides-export dist/

# Avoid breaking existing links
mkdir -p dist/prez/sli.dev/
ln -s ../.. dist/prez/sli.dev/dist

# For Cover PNG linked from https://github.com/slidevjs/docs/pull/188
ln -s slides-export dist/png

npm run export-pdf
