#!/usr/bin/env bash
set -euxo pipefail

npm install

npm run build

# https://github.com/slidevjs/slidev/issues/1872
if [ ! -f /usr/local/share/fonts/NotoColorEmoji.ttf ]; then
  curl -L --output NotoColorEmoji.ttf https://github.com/googlefonts/noto-emoji/raw/main/fonts/NotoColorEmoji.ttf
  sudo mv NotoColorEmoji.ttf /usr/local/share/fonts/
  fc-cache -fv
fi

npm run export-md-png

npm run export-pdf
